# Generated by Django 5.2.8 on 2025-11-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='location_id',
        ),
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.location'),
        ),
    ]
