# Generated by Django 5.2.8 on 2025-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_location_remove_character_location_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='epithet',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Location selected'), (9, 'Done')], default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
